apiVersion: v1
kind: Service
metadata:
  name: backend-user
  namespace: project-3
  labels:
    udagram-app: backend-user
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    udagram-app: backend-user
