apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  namespace: project-3
  labels:
    udagram-app: backend-feed
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    udagram-app: backend-feed
