apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  namespace: project-3
  labels:
    udagram-app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      udagram-app: backend-user
  template:
    metadata:
      labels:
        udagram-app: backend-user
    spec:
      containers:
        - name: backend-user
          image: duynam89/udagram-api-user
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: postgres-password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: postgres-host
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: postgres-db
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws-bucket
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws-region
            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws-profile
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws-access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws-secret-access-key
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: jwt-secret
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: url
