apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: project-3
  labels:
    udagram-app: frontend
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    udagram-app: frontend
