apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: project-3
  labels:
    udagram-app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      udagram-app: frontend
  template:
    metadata:
      labels:
        udagram-app: frontend
    spec:
      containers:
        - name: frontend
          image: duynam89/udagram-frontend
          ports:
            - containerPort: 80
