apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  namespace: project-3
  labels:
    udagram-app: reverseproxy
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    udagram-app: reverseproxy
